# This workflow will upload a docker image
# to https://hub.docker.com/repository/docker/twindb/omnibus-ubuntu
---
name: Continuous Deployment

on:  # yamllint disable-line rule:truthy
    push:
        branches: ["noble"]
jobs:
    push_to_registry:
        name: "Push Docker image to Docker Hub"
        runs-on: ${{matrix.os}}
        strategy:
            matrix:
                os: ["ubuntu-latest", "macos-14"]

        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            # Credit https://stackoverflow.com/a/58035262
            - name: Extract branch name
              shell: bash
              run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
              id: extract_branch

            - name: "Install Docker"
              if: "${{matrix.os == 'macos-14'}}"
              run: |
                wget https://desktop.docker.com/mac/main/arm64/Docker.dmg
                sudo hdiutil attach Docker.dmg
                sudo /Volumes/Docker/Docker.app/Contents/MacOS/install --accept-license
                sudo hdiutil detach /Volumes/Docker

            - name: "Log in to Docker Hub"
              uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: "Build and push the image"
              run: |
                ARCH=$(uname -m)
                docker build -t twindb/omnibus-ubuntu:${{ steps.extract_branch.outputs.branch }}-${ARCH} .
                docker push twindb/omnibus-ubuntu:${{ steps.extract_branch.outputs.branch }}-${ARCH}
